### PR TITLE
Add features to mimic xq (from python yq)

### PR DESCRIPTION
**Pull request by momiji**
Added a few features, without any breaking changes:
- add KeepNamespace() to keep namespaces in input
- add ForceList() to force elements to be arrays
- add FixRoot() to prevent adding root element when map/Map contains only one element

Also added tests for these new features.

### CODE REVIEW

**Comment by clbanning** [comment]
The `ForceList()` option seems a little orthogonal to the spirit of this package in that it doesn't differentiate sub-element tags using dot-notation.   I am aware that `xq` has its origin with `yaml` docs and has, perhaps, a limited view of the complexity of the XML docs for which it would be used.

I'd prefer to have two separate functions in the spirit of `(Map)ValuesForKey` and `(Map)ValuesForPath` that could be invoked as desired.  Say, `(Map)ForceListKeys` and `(Map)ForceListPaths`.

I'm guessing that the `FixRoot()` is required to support XML marshaling of a Map that has been unmarshaled using the `ForceList()` option.  Perhaps there should be a couple of cleanup methods, such as `(Map)RemoveListKeys` and `MapRemoveListPaths` that would complement the `ForceList` methods and would be invoked prior to `(Map)Xml`.

**Comment by momiji** [comment]
Thank you for your answer.

I understand your point for `ForceListForKey` and `ForceListForMap` as it makes sense, although not sure how to implement the path part, but I can have a look to `ValuesForPath`.

For `FixRoot`, I found problematic that `<r><e>1</e></r>` => NewMapXml => AnyXml => `<doc><r><e>1</e></r></doc>`, which is not what I want. My guess nobody had this need before, and this only applies to the root, nothing else.

For the story, my target is to add mxj to gojq to have xml support, exatly the same way as xq.

**Comment by momiji** [comment]
It's done!

```sh
$ echo -e "<x><y>2</y></x>"  | ./xjq -X --xml-force-list x.y -c -x
<x><y>2</y></x>

$ echo -e "<x><y>2</y></x>"  | ./xjq -X --xml-force-list x.y -c
{"x":{"y":[2]}}
```

**Comment by momiji** [comment]
Please hold on this PR until I'm completely satisfied.
I'm still actively doing tests and corrections.

**Comment by momiji** [comment]
Hello, I ended by reimplementing parser/writer, as I found mxj to be slower than original xq.
Which is normal as it is more generalist than needed, to I finally wrote my own package.
Thank you for you suggestions anyway.

**Pull request closed without merging**
