### PR TITLE
memleak in cast func

### PR DESCRIPTION
**Pull request by candiduslynx**

### CODE REVIEW

**Comment by clbanning** [comment]
I merged your request for purely stylistic reasons.  Can you provide the evidence that <i><b>casting a local variable</b></i> causes a memory leak?  I have never seen that behavior.

**Comment by Slania** [comment]
I was wondering the same thing @clbanning.

Maybe the OP means unnecessary memory allocation? A leak would require a dangling reference that can't be swept. In this case you're returning an `interface{}` which would be alloc'd on the heap, but when the receiving reference scopes out, it should get swept.

**Comment by candiduslynx** [comment]
It's actually caused by a string casting mostly (because in go strings are immutable and casting is actually providing a copy of string).

You can try calling NewMapXml with a LARGE file (like, 6000 lines) and pprof this to see what I'm talking about.

**Comment by candiduslynx** [comment]
It leaks

**Comment by Slania** [comment]
@clbanning I did, here is my setup:

```bash
go1.10.1 darwin/amd64, OS X v10.12.6
```

Here are my results:
```golang
clm-C02V90ERHTDG:tab(queued_blob_rework)$ go run foo.go
castold.go ---------
b==true
0 : HeapAlloc 108080 HeapInuse 335872 HeapObjects 148 NumGC 0 Frees 2
10000000 : HeapAlloc 1017520 HeapInuse 1228800 HeapObjects 26282 NumGC 296 Frees 39973917
20000000 : HeapAlloc 1947296 HeapInuse 2154496 HeapObjects 53396 NumGC 592 Frees 79946820
30000000 : HeapAlloc 2882144 HeapInuse 3096576 HeapObjects 80660 NumGC 888 Frees 119919572
40000000 : HeapAlloc 3814640 HeapInuse 4038656 HeapObjects 107856 NumGC 1184 Frees 159892391
50000000 : HeapAlloc 701568 HeapInuse 917504 HeapObjects 17056 NumGC 1481 Frees 199983206
60000000 : HeapAlloc 1638128 HeapInuse 1851392 HeapObjects 44369 NumGC 1777 Frees 239955909
70000000 : HeapAlloc 2571936 HeapInuse 2785280 HeapObjects 71603 NumGC 2073 Frees 279928690
80000000 : HeapAlloc 3509936 HeapInuse 3735552 HeapObjects 98958 NumGC 2369 Frees 319901351
90000000 : HeapAlloc 697072 HeapInuse 917504 HeapObjects 16867 NumGC 2666 Frees 359983459
b==false
0 : HeapAlloc 2251272 HeapInuse 2473984 HeapObjects 62166 NumGC 2962 Frees 399938179
10000000 : HeapAlloc 2876080 HeapInuse 3112960 HeapObjects 172112 NumGC 3080 Frees 429828241
20000000 : HeapAlloc 3516912 HeapInuse 3760128 HeapObjects 212154 NumGC 3198 Frees 459788215
30000000 : HeapAlloc 4157552 HeapInuse 4399104 HeapObjects 252194 NumGC 3316 Frees 489748189
40000000 : HeapAlloc 733344 HeapInuse 974848 HeapObjects 38181 NumGC 3435 Frees 519962218
50000000 : HeapAlloc 1382432 HeapInuse 1622016 HeapObjects 78736 NumGC 3553 Frees 549921680
60000000 : HeapAlloc 2023168 HeapInuse 2260992 HeapObjects 118777 NumGC 3671 Frees 579881654
70000000 : HeapAlloc 2663808 HeapInuse 2899968 HeapObjects 158817 NumGC 3789 Frees 609841628
80000000 : HeapAlloc 3304448 HeapInuse 3547136 HeapObjects 198857 NumGC 3907 Frees 639801602
90000000 : HeapAlloc 3945088 HeapInuse 4186112 HeapObjects 238897 NumGC 4025 Frees 669761576
clm-C02V90ERHTDG:tab(queued_blob_rework)$ go run baz.go 
castnew.go ------------
b==true
0 : HeapAlloc 108704 HeapInuse 409600 HeapObjects 151 NumGC 0 Frees 2
10000000 : HeapAlloc 1012592 HeapInuse 1277952 HeapObjects 26281 NumGC 296 Frees 39973912
20000000 : HeapAlloc 1946784 HeapInuse 2211840 HeapObjects 53473 NumGC 592 Frees 79946741
30000000 : HeapAlloc 2868960 HeapInuse 3137536 HeapObjects 80368 NumGC 888 Frees 119919861
40000000 : HeapAlloc 3800912 HeapInuse 4063232 HeapObjects 107547 NumGC 1184 Frees 159892698
50000000 : HeapAlloc 681216 HeapInuse 950272 HeapObjects 16555 NumGC 1481 Frees 199983705
60000000 : HeapAlloc 1609776 HeapInuse 1875968 HeapObjects 43589 NumGC 1777 Frees 239956688
70000000 : HeapAlloc 2540448 HeapInuse 2809856 HeapObjects 70730 NumGC 2073 Frees 279929563
80000000 : HeapAlloc 3472592 HeapInuse 3743744 HeapObjects 97917 NumGC 2369 Frees 319902390
90000000 : HeapAlloc 353280 HeapInuse 647168 HeapObjects 6934 NumGC 2666 Frees 359993389
b==false
0 : HeapAlloc 1284936 HeapInuse 1548288 HeapObjects 34077 NumGC 2962 Frees 399966264
10000000 : HeapAlloc 942048 HeapInuse 1236992 HeapObjects 51443 NumGC 3080 Frees 429948907
20000000 : HeapAlloc 624320 HeapInuse 917504 HeapObjects 31580 NumGC 3198 Frees 459968785
30000000 : HeapAlloc 306496 HeapInuse 598016 HeapObjects 11716 NumGC 3316 Frees 489988663
40000000 : HeapAlloc 4059648 HeapInuse 4349952 HeapObjects 246288 NumGC 3433 Frees 519754105
50000000 : HeapAlloc 3741824 HeapInuse 4030464 HeapObjects 226424 NumGC 3551 Frees 549773983
60000000 : HeapAlloc 3424096 HeapInuse 3719168 HeapObjects 206561 NumGC 3669 Frees 579793861
70000000 : HeapAlloc 3106560 HeapInuse 3399680 HeapObjects 186700 NumGC 3787 Frees 609813739
80000000 : HeapAlloc 2788736 HeapInuse 3080192 HeapObjects 166836 NumGC 3905 Frees 639833617
90000000 : HeapAlloc 2470912 HeapInuse 2760704 HeapObjects 146972 NumGC 4023 Frees 669853495
```

So this is what I have concluded:
* First off my results are within rounding errors of each other across both those snippets of code.
* Second, as predicted, there is furious alloc'ing and dealloc'ing as observed by the `HeapAlloc` and `Frees` metrics. If there was a leak, I would have expected `HeapAlloc` to have grown like crazy and very little to have been freed by GC runs.
* Thirdly and finally I guess what got missed was that there is implicit internal type conversion that Go does to return `interface{}` which would alloc anyway, so overall this PR improves readability and that's about it.

Waiting to hear where I am wrong :)

**Comment by clbanning** [comment]
That's my point - why I accepted the pull request as a stylistic improvement not a memory leak. I would have thought the Russ Cox blog entry would be definitive but then wrote the demo code just to confirm it for those who haven't been  working with go since 2009.

**Comment by Slania** [comment]
👍 cool, nice article by the way, thanks for the link!

**Pull request merged**
