### PR TITLE
Revert "Added ability for a user to specify if keys should be in snake case"

### PR DESCRIPTION
**Pull request by clbanning**
Reverts clbanning/mxj#32

### CODE REVIEW

**Comment by clbanning** [comment]
Do you have attribute keys that require snake case?  Currently implementation does not pass my test case.

```
package mxj

import (
   "fmt"
   "testing"
)  
      
func TestStakeCase(t *testing.T) {
   PrependAttrWithHyphen(true)
   fmt.Println("\n----------- TestSnakeCase")
   CoerceKeysToSnakeCase()

   data1 := `<xml-rpc><element-one attr1="an attribute">something</element-one></xml-rpc>`
   data2 := `<xml_rpc><element_one attr1="an attribute">something</element_one></xml_rpc>`
   
   m, err := NewMapXml([]byte(data1))
   if err != nil {
      t.Fatal(err)
   }
   fmt.Println(m)
   
   x, err := m.Xml()
   if err != nil {
      t.Fatal(err)
   }  
   if string(x) != data2 {
      t.Fatal(string(x), "!=", data2)
   }     
} 
```

**Comment by charl** [comment]
Yes:

```xml
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/11.2R4/junos" message-id="97741fa3-99e8-46ba-b103-bab6b459d884">
<software-information>
<host-name>srx100</host-name>
<product-model>srx100b</product-model>
<product-name>srx100b</product-name>
<jsr/>
<package-information>
<name>junos</name>
<comment>JUNOS Software Release [11.2R4.3]</comment>
</package-information>
</software-information>
</rpc-reply>
```

_message-id_ is an example  in the above code.

**Comment by clbanning** [comment]
You do realize that NewMapXml()/mv.Xml() will strip namespace references.  If all you wanting to do is change attribute and element tags to snakecase and preserve the namespace attributes as well as the structure of the message you need to use NewMapXmlSeq()/mv.XmlSeq().  I"ll add that later today.

**Comment by clbanning** [comment]
I've updated NewMapXmlSeq/mv.XmlSeq to handle your use-case.  See snake case_test.go.

**Pull request merged**
